# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 22, 16, 39, 12, 614794, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 22, 16, 39, 16, 917829, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
