# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160523_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='smell',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 23, 7, 16, 41, 66861, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smell',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 23, 7, 16, 43, 547220, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booleanmetric',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booleans', to='api.Build'),
        ),
    ]
